package com.java.exception;

import java.util.Scanner;

public class ThrowEx {
	
	public void check(int n) {
		if(n<0) {
			throw new ArithmeticException("Negative number are not allowed");
		}else if(n==0) {
			throw new NumberFormatException("Zero is Invalid value");
		}else {
			System.out.println("N value is "+n);
		}
	}
	
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter value of n ");
		int n = sc.nextInt();
		
		ThrowEx obj = new ThrowEx();
		try {
			obj.check(n);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
