package com.java.exception;

public class ArrayEx {
	
	public static void main(String[] args) {
		
		int[] arr = {12,8,5};
		
		try {
			arr[9]=7;
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		for (int i : arr) {
			System.out.println(i);			
		}
	}

}
